export const categoryList = [
  'Adventure & Sports',
  'Art & Culture',
  'Food & Drink',
  'Historical Sites',
  'Nature & Outdoors',
  'Nightlife & Entertainment',
  'Relaxation & Wellness',
  'Shopping',
  'Unusual Experiences',
];

export const countyList = [
  'Antrim',
  'Armagh',
  'Carlow',
  'Cavan',
  'Clare',
  'Cork',
  'Derry',
  'Donegal',
  'Down',
  'Dublin',
  'Fermanagh',
  'Galway',
  'Kerry',
  'Kildare',
  'Kilkenny',
  'Laois',
  'Leitrim',
  'Limerick',
  'Longford',
  'Louth',
  'Mayo',
  'Meath',
  'Monaghan',
  'Offaly',
  'Roscommon',
  'Sligo',
  'Tipperary',
  'Tyrone',
  'Waterford',
  'Westmeath',
  'Wexford',
  'Wicklow',
];
